plugins {
    id "fabric-loom" version "1.9-SNAPSHOT" apply false
}

allprojects {
    apply plugin: "java"

    tasks.withType(JavaCompile) {
        options.encoding = "UTF-8"
        options.release = 21
    }

    java {
        toolchain {
            languageVersion = JavaLanguageVersion.of(21)
        }
    }
}
