schema_version = 1

[target]
nms_version = "7.01"
branch = "public"
steam_build_ids = ["25233815"]

[hgpaktool]
package = "hgpaktool"
version = "1.1.3"
platform = "windows"

[mbincompiler]
release = "v7.01.0-pre1"
reported_version = "7.01.0.1"
filename = "MBINCompiler-linux"
url = "https://github.com/monkeyman192/MBINCompiler/releases/download/v7.01.0-pre1/MBINCompiler-linux"
sha256 = "47f96b7607f415d0739e1f694190ff4b0fcd5096c42956146f3538bcd209bc56"
dotnet_major = 8
container_image = "mcr.microsoft.com/dotnet/runtime@sha256:9cfa8aaf5c98a4cedffec74d450dd2d4510ba72ee9e663efe2658500b0321524"
