schema: 1

globals:
  default_profile: default

  profiles:
    quick:
      tests: [build, server-smoke]

    default:
      tests: [build, server-smoke, pregen]
      max_jobs: 32

    extended:
      extends: default
      max_jobs: 64

  tests:
    pregen:
      config:
        preset: xs
        tool_preference: [chunksmith, chunky]
