/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GamesRouteRouteImport } from './routes/games/route'
import { Route as GamesIndexRouteImport } from './routes/games/index'
import { Route as GamesGameSlugRouteRouteImport } from './routes/games/$gameSlug/route'
import { Route as GamesGameSlugIndexRouteImport } from './routes/games/$gameSlug/index'
import { Route as GamesGameSlugModsRouteRouteImport } from './routes/games/$gameSlug/mods/route'
import { Route as GamesGameSlugModsModSlugRouteImport } from './routes/games/$gameSlug/mods/$modSlug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesRouteRoute = GamesRouteRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesIndexRoute = GamesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GamesRouteRoute,
} as any)
const GamesGameSlugRouteRoute = GamesGameSlugRouteRouteImport.update({
  id: '/$gameSlug',
  path: '/$gameSlug',
  getParentRoute: () => GamesRouteRoute,
} as any)
const GamesGameSlugIndexRoute = GamesGameSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GamesGameSlugRouteRoute,
} as any)
const GamesGameSlugModsRouteRoute = GamesGameSlugModsRouteRouteImport.update({
  id: '/mods',
  path: '/mods',
  getParentRoute: () => GamesGameSlugRouteRoute,
} as any)
const GamesGameSlugModsModSlugRoute =
  GamesGameSlugModsModSlugRouteImport.update({
    id: '/$modSlug',
    path: '/$modSlug',
    getParentRoute: () => GamesGameSlugModsRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/games': typeof GamesRouteRouteWithChildren
  '/games/$gameSlug': typeof GamesGameSlugRouteRouteWithChildren
  '/games/': typeof GamesIndexRoute
  '/games/$gameSlug/mods': typeof GamesGameSlugModsRouteRouteWithChildren
  '/games/$gameSlug/': typeof GamesGameSlugIndexRoute
  '/games/$gameSlug/mods/$modSlug': typeof GamesGameSlugModsModSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/games': typeof GamesIndexRoute
  '/games/$gameSlug/mods': typeof GamesGameSlugModsRouteRouteWithChildren
  '/games/$gameSlug': typeof GamesGameSlugIndexRoute
  '/games/$gameSlug/mods/$modSlug': typeof GamesGameSlugModsModSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/games': typeof GamesRouteRouteWithChildren
  '/games/$gameSlug': typeof GamesGameSlugRouteRouteWithChildren
  '/games/': typeof GamesIndexRoute
  '/games/$gameSlug/mods': typeof GamesGameSlugModsRouteRouteWithChildren
  '/games/$gameSlug/': typeof GamesGameSlugIndexRoute
  '/games/$gameSlug/mods/$modSlug': typeof GamesGameSlugModsModSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/games'
    | '/games/$gameSlug'
    | '/games/'
    | '/games/$gameSlug/mods'
    | '/games/$gameSlug/'
    | '/games/$gameSlug/mods/$modSlug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/games'
    | '/games/$gameSlug/mods'
    | '/games/$gameSlug'
    | '/games/$gameSlug/mods/$modSlug'
  id:
    | '__root__'
    | '/'
    | '/games'
    | '/games/$gameSlug'
    | '/games/'
    | '/games/$gameSlug/mods'
    | '/games/$gameSlug/'
    | '/games/$gameSlug/mods/$modSlug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GamesRouteRoute: typeof GamesRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games': {
      id: '/games'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof GamesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/': {
      id: '/games/'
      path: '/'
      fullPath: '/games/'
      preLoaderRoute: typeof GamesIndexRouteImport
      parentRoute: typeof GamesRouteRoute
    }
    '/games/$gameSlug': {
      id: '/games/$gameSlug'
      path: '/$gameSlug'
      fullPath: '/games/$gameSlug'
      preLoaderRoute: typeof GamesGameSlugRouteRouteImport
      parentRoute: typeof GamesRouteRoute
    }
    '/games/$gameSlug/': {
      id: '/games/$gameSlug/'
      path: '/'
      fullPath: '/games/$gameSlug/'
      preLoaderRoute: typeof GamesGameSlugIndexRouteImport
      parentRoute: typeof GamesGameSlugRouteRoute
    }
    '/games/$gameSlug/mods': {
      id: '/games/$gameSlug/mods'
      path: '/mods'
      fullPath: '/games/$gameSlug/mods'
      preLoaderRoute: typeof GamesGameSlugModsRouteRouteImport
      parentRoute: typeof GamesGameSlugRouteRoute
    }
    '/games/$gameSlug/mods/$modSlug': {
      id: '/games/$gameSlug/mods/$modSlug'
      path: '/$modSlug'
      fullPath: '/games/$gameSlug/mods/$modSlug'
      preLoaderRoute: typeof GamesGameSlugModsModSlugRouteImport
      parentRoute: typeof GamesGameSlugModsRouteRoute
    }
  }
}

interface GamesGameSlugModsRouteRouteChildren {
  GamesGameSlugModsModSlugRoute: typeof GamesGameSlugModsModSlugRoute
}

const GamesGameSlugModsRouteRouteChildren: GamesGameSlugModsRouteRouteChildren =
  {
    GamesGameSlugModsModSlugRoute: GamesGameSlugModsModSlugRoute,
  }

const GamesGameSlugModsRouteRouteWithChildren =
  GamesGameSlugModsRouteRoute._addFileChildren(
    GamesGameSlugModsRouteRouteChildren,
  )

interface GamesGameSlugRouteRouteChildren {
  GamesGameSlugModsRouteRoute: typeof GamesGameSlugModsRouteRouteWithChildren
  GamesGameSlugIndexRoute: typeof GamesGameSlugIndexRoute
}

const GamesGameSlugRouteRouteChildren: GamesGameSlugRouteRouteChildren = {
  GamesGameSlugModsRouteRoute: GamesGameSlugModsRouteRouteWithChildren,
  GamesGameSlugIndexRoute: GamesGameSlugIndexRoute,
}

const GamesGameSlugRouteRouteWithChildren =
  GamesGameSlugRouteRoute._addFileChildren(GamesGameSlugRouteRouteChildren)

interface GamesRouteRouteChildren {
  GamesGameSlugRouteRoute: typeof GamesGameSlugRouteRouteWithChildren
  GamesIndexRoute: typeof GamesIndexRoute
}

const GamesRouteRouteChildren: GamesRouteRouteChildren = {
  GamesGameSlugRouteRoute: GamesGameSlugRouteRouteWithChildren,
  GamesIndexRoute: GamesIndexRoute,
}

const GamesRouteRouteWithChildren = GamesRouteRoute._addFileChildren(
  GamesRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GamesRouteRoute: GamesRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
